print ("Welcome to the power calculator!")
base = (input ("Enter the base: "))
exponent =  (input ("Enter the exponent: "))
power = pow(base,exponent)
print ("%s to the power of  %s is %s" % (str(base), str(exponent), str(power)))
